// <auto-generated />
using CINEKONG.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace CINEKONG.Migrations
{
    [DbContext(typeof(CinekongContext))]
    [Migration("20181103233427_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("CINEKONG.Models.Usuario", b =>
                {
                    b.Property<string>("Correo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100);

                    b.Property<string>("Apellidos")
                        .IsRequired();

                    b.Property<string>("Contraseña")
                        .IsRequired();

                    b.Property<DateTime>("FecNac");

                    b.Property<string>("Nombres")
                        .IsRequired();

                    b.HasKey("Correo");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
