// <auto-generated />
using System;
using CINEKONG.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CINEKONG.Migrations
{
    [DbContext(typeof(CinekongContext))]
    [Migration("20181102012218_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CINEKONG.Models.Usuario", b =>
                {
                    b.Property<string>("Contraseña")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Correo");

                    b.Property<DateTime>("FecNac");

                    b.Property<string>("Nombres")
                        .IsRequired();

                    b.HasKey("Contraseña");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
