// <auto-generated />
using CINEKONG.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace CINEKONG.Migrations
{
    [DbContext(typeof(CinekongContext))]
    partial class CinekongContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("CINEKONG.Models.Butaca", b =>
                {
                    b.Property<string>("idbut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30);

                    b.Property<string>("estbut");

                    b.Property<string>("tipbut");

                    b.HasKey("idbut");

                    b.ToTable("Butaca");
                });

            modelBuilder.Entity("CINEKONG.Models.Usuario", b =>
                {
                    b.Property<string>("Correo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100);

                    b.Property<string>("Apellidos")
                        .IsRequired();

                    b.Property<string>("Contraseña")
                        .IsRequired();

                    b.Property<DateTime>("FecNac");

                    b.Property<string>("Nombres")
                        .IsRequired();

                    b.HasKey("Correo");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CINEKONG.Models.UsuarioButaca", b =>
                {
                    b.Property<string>("idbut");

                    b.Property<string>("Correo");

                    b.Property<int>("cantidad");

                    b.Property<double>("costo");

                    b.Property<double>("subtotal");

                    b.HasKey("idbut", "Correo");

                    b.HasIndex("Correo");

                    b.ToTable("UsuarioButaca");
                });

            modelBuilder.Entity("CINEKONG.Models.UsuarioButaca", b =>
                {
                    b.HasOne("CINEKONG.Models.Usuario", "usuario")
                        .WithMany("UsuarioButacas")
                        .HasForeignKey("Correo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CINEKONG.Models.Butaca", "butaca")
                        .WithMany("UsuarioButacas")
                        .HasForeignKey("idbut")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
